-- FLEXFANG Trade CRM v0.1
-- Phase 1: non-invasive trade profile extension for existing CRM entities.
-- Target: MySQL 8.x

CREATE TABLE IF NOT EXISTS `crm_trade_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `biz_type` int NOT NULL COMMENT 'CRM 业务类型：1线索 2客户 4商机',
  `biz_id` bigint NOT NULL COMMENT 'CRM 业务编号',
  `country_code` varchar(8) DEFAULT NULL COMMENT 'ISO 国家/地区代码',
  `region` varchar(128) DEFAULT NULL COMMENT '州/省/大区',
  `city` varchar(128) DEFAULT NULL COMMENT '城市',
  `company_type` varchar(32) DEFAULT NULL COMMENT '客户类型',
  `source_channel` varchar(32) DEFAULT NULL COMMENT '来源渠道',
  `website` varchar(512) DEFAULT NULL COMMENT '公司网站',
  `whatsapp` varchar(64) DEFAULT NULL COMMENT 'WhatsApp',
  `linkedin` varchar(512) DEFAULT NULL COMMENT 'LinkedIn',
  `import_experience` bit(1) DEFAULT NULL COMMENT '是否有进口经验',
  `annual_purchase_volume` decimal(18,2) DEFAULT NULL COMMENT '预估年采购额',
  `target_products` varchar(1000) DEFAULT NULL COMMENT '目标产品',
  `expected_moq` int DEFAULT NULL COMMENT '预期 MOQ',
  `target_price` decimal(18,4) DEFAULT NULL COMMENT '目标单价',
  `currency` varchar(8) DEFAULT NULL COMMENT '币种',
  `certification_requirement` varchar(512) DEFAULT NULL COMMENT '认证要求',
  `incoterm` varchar(16) DEFAULT NULL COMMENT '贸易条款',
  `destination_port` varchar(128) DEFAULT NULL COMMENT '目的港',
  `sample_status` varchar(32) DEFAULT NULL COMMENT '样品状态',
  `container_potential` varchar(16) DEFAULT NULL COMMENT '集装箱潜力',
  `fcl_probability` tinyint unsigned DEFAULT NULL COMMENT '整柜成交概率 0-100',
  `lead_score` tinyint unsigned DEFAULT NULL COMMENT '线索评分 0-100',
  `risk_score` tinyint unsigned DEFAULT NULL COMMENT '风险评分 0-100',
  `next_action` varchar(512) DEFAULT NULL COMMENT '下一步动作',
  `lost_reason` varchar(512) DEFAULT NULL COMMENT '丢单原因',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_crm_trade_profile_biz` (`tenant_id`, `biz_type`, `biz_id`, `deleted`),
  KEY `idx_crm_trade_profile_country` (`tenant_id`, `country_code`),
  KEY `idx_crm_trade_profile_company_type` (`tenant_id`, `company_type`),
  KEY `idx_crm_trade_profile_source` (`tenant_id`, `source_channel`),
  KEY `idx_crm_trade_profile_container` (`tenant_id`, `container_potential`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM 外贸档案';
