-- FLEXFANG Trade CRM v0.1
-- Versioned foreign-trade quotation. Target MySQL 8.x.

CREATE TABLE IF NOT EXISTS `crm_trade_quotation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `no` varchar(64) NOT NULL COMMENT '报价系列编号',
  `revision` int NOT NULL DEFAULT 1 COMMENT '修订版本',
  `previous_quotation_id` bigint DEFAULT NULL COMMENT '上一版本报价编号',
  `rfq_id` bigint DEFAULT NULL COMMENT 'RFQ编号',
  `customer_id` bigint NOT NULL COMMENT '客户编号',
  `business_id` bigint DEFAULT NULL COMMENT '商机编号',
  `owner_user_id` bigint NOT NULL COMMENT '负责人',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/SENT/ACCEPTED/REJECTED/SUPERSEDED/CANCELLED',
  `issue_time` datetime DEFAULT NULL COMMENT '报价日期',
  `valid_until` datetime DEFAULT NULL COMMENT '有效期至',
  `currency` varchar(8) NOT NULL COMMENT '币种',
  `incoterm` varchar(16) DEFAULT NULL COMMENT '贸易条款',
  `destination_port` varchar(128) DEFAULT NULL COMMENT '目的港/指定地点',
  `payment_terms` varchar(512) DEFAULT NULL COMMENT '付款条款',
  `lead_time_days` int DEFAULT NULL COMMENT '交期天数',
  `packaging_terms` varchar(512) DEFAULT NULL COMMENT '包装条款',
  `subtotal` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '产品小计',
  `discount_amount` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `freight` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '运费',
  `insurance` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '保险费',
  `other_charge` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '其他费用',
  `total_amount` decimal(18,4) NOT NULL DEFAULT 0 COMMENT '报价总额',
  `sent_time` datetime DEFAULT NULL COMMENT '发送时间',
  `accepted_time` datetime DEFAULT NULL COMMENT '客户接受时间',
  `rejection_reason` varchar(512) DEFAULT NULL COMMENT '拒绝原因',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_crm_trade_quotation_revision` (`tenant_id`,`no`,`revision`,`deleted`),
  KEY `idx_crm_trade_quotation_rfq` (`tenant_id`,`rfq_id`),
  KEY `idx_crm_trade_quotation_customer` (`tenant_id`,`customer_id`),
  KEY `idx_crm_trade_quotation_owner_status` (`tenant_id`,`owner_user_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM 外贸报价';

CREATE TABLE IF NOT EXISTS `crm_trade_quotation_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `quotation_id` bigint NOT NULL COMMENT '报价编号',
  `product_id` bigint DEFAULT NULL COMMENT 'CRM产品编号',
  `product_name` varchar(255) NOT NULL COMMENT '产品名称快照',
  `specification` varchar(512) DEFAULT NULL COMMENT '规格要求',
  `quantity` int NOT NULL COMMENT '数量',
  `unit_price` decimal(18,4) NOT NULL COMMENT '单价',
  `line_amount` decimal(18,4) NOT NULL COMMENT '行金额',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_crm_trade_quotation_item_quote` (`tenant_id`,`quotation_id`),
  KEY `idx_crm_trade_quotation_item_product` (`tenant_id`,`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CRM 外贸报价明细';
